$script_mysql = <<-SCRIPT
  apt-get update && \
  apt-get install -y mysql-server && \
  mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|  
  config.vm.box = "ubuntu/focal64"
  
  #config.vm.network "private_network", ip: "192.168.56.0" 
  
 
  config.vm.define "mysqldb" do |mysql|

    mysql.vm.network "public_network", ip: "172.16.31.43"
    mysql.vm.provision "shell", 
      inline: "cat /configs/shh-keys.pub >> .ssh/authorized_keys"
    mysql.vm.provision "shell", inline: $script_mysql
    mysql.vm.provision "shell", 
      inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    mysql.vm.provision "shell",
      inline: "service mysql restart"
    mysql.vm.synced_folder "./configs", "/configs"
    mysql.vm.synced_folder ".", "/vagrant", disabled: true
  
    end
  
  config.vm.define "phpweb" do |phpweb|
    
    phpweb.vm.network "forwarded_port", guest: 8888, host: 8888
    phpweb.vm.network "public_network", ip: "172.16.31.44"
    
    phpweb.vm.provision "shell", 
    inline: "apt-get update && apt-get install -y puppet"
    
    phpweb.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "./configs/manifests"
      puppet.manifest_file = "phpweb.pp"
      end
    end
  
  config.vm.define "mysqlserver" do |mysqlserver|
    mysqlserver.vm.network "public_network", ip: "172.16.31.45"
    mysqlserver.vm.provision "shell", 
      inline: "cat /vagrant/configs/shh-keys.pub >> .ssh/authorized_keys"
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "172.16.31.46"
    
    ansible.vm.provision "shell",
      inline: "cp /vagrant/shh-keys /home/vagrant && \
      chmod 600 /home/vagrant/shh-keys && \
      chown vagrant:vagrant /home/vagrant/shh-keys"  # Verificar Amanhã (31/08/2022) pois o Ansible não está conseguindo acessar a mysqlserver por ssh.
    ansible.vm.provision"shell", 
      inline: "apt-get update && \
      apt-get install -y software-properties-common && \
      add-apt-repository --yes --update ppa:ansible/ansible && \
      apt-get install -y ansible"
  end
end